// DO NOT MODIFY THIS FILE OR YOUR CHANGES WILL BE LOST!
// This file is generated by GenerateHTML.sh
// Last generated on Thu Apr 25 19:28:18 CST 2024

import File0 from './HTML/Home.html';
import File1 from './HTML/Home.js';
import File2 from './HTML/index.css';
import File3 from './HTML/index.html';
import File4 from './HTML/index.js';

const StaticFiles = {
    'Home.html': File0,
    'Home.js': File1,
    'index.css': File2,
    'index.html': File3,
    'index.js': File4,
};

export class HTML {
    private Path: string;
    constructor(Path: string) {
        this.Path = Path;
    }

    public Process(): object {
        let ResponseData = {
            Data: '',
            ContentType: 'text/plain',
        };
        if (this.Path in StaticFiles) {
            ResponseData.Data = StaticFiles[this.Path];
            if (this.Path.endsWith('.html')) {
                ResponseData.ContentType = 'text/html';
            } else if (this.Path.endsWith('.js')) {
                ResponseData.ContentType = 'text/javascript';
            } else if (this.Path.endsWith('.css')) {
                ResponseData.ContentType = 'text/css';
            }
        }
        else {
            ResponseData.Data = '404 Not Found';
        }
        return ResponseData;
    }
}
